services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PYTHON_VERSION: "3.12"
    image: "hunt_framework/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - ".:/app"
      - "/app/.venv"
    networks:
      - lodge

networks:
  lodge:
    driver: bridge
